### ISSUE TITLE
Final group capstone: set up Kanban board

### ISSUE THREAD

**Issue by K0ppai** [K0ppai/yacht-rental-backend#12]
Hello reviewers,
We're a three people team including me(@K0ppai), @HtetWaiYan7191, and @YoutLone. This [link](https://github.com/K0ppai/yacht-rental-backend/projects/1) is our project link. Thank you for reviewing our project. 😁 

![image](https://github.com/K0ppai/yacht-rental-backend/assets/113283174/f6e8c65f-568c-49fe-a458-7f69dbd468d9)

**Comment by Meltrust** [comment]
Hi @K0ppai,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed and have descriptions.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
